# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: false
language: node_js
node_js:
    - "6"
    - "8"
    - "10"
    - stable
git:
    depth: 1

script:
    - npm run lint
    - npm test

# 自动发布
deploy:
    - provider: npm
      email: npmjs@newfututre.cc
      api_key: "${NPM_TOKEN}"
      skip_cleanup: true
      on:
          tags: true
          branch: master
