# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: false
language: node_js
node_js:
    - "6"
    - "8"
    - "10"
    - stable
git:
    depth: 1

script:
  - npm run lint
  - npm run build
  - npm test